### ISSUE TITLE
Delete entry from wordlist so that hackers can't delete my school bus 

### ISSUE THREAD

**Issue by rew1nter** [Escape-Technologies/graphql-wordlist#1]
This has me very concerned and I fear that my school bus may be deleted from the system. As a result, I could miss the class. Please delete this so I can attend my class without any interference
![image](https://github.com/Escape-Technologies/graphql-wordlist/assets/64508791/2839a4cb-7008-4c85-9182-52d39c0b5483)

**Comment by nohehf** [comment]
Ahaha nice catch, didn't expect such mutations to exists 🚌
